default: &default
  adapter: postgresql
  encoding: unicode
  username: third-party-retargeter
  password:
  host: localhost
  port: 5432
  pool: 5

development:
  <<: *default
  database: third-party-retargeter_development

test:
  <<: *default
  database: third-party-retargeter_test

#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
production:
  url: <%= ENV['DATABASE_URL'] %>

